name: Deploy to Release

on:
  push:
    branches:
      - Release
  workflow_dispatch:

jobs:
  deploy-release:
    runs-on: windows-latest
    environment: 
      name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/Release' && github.event.workflow_dispatch
    steps:
      # - uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ secrets.GITHUBTOKEN }}
      #     approvers: rinizelar,Bhargavnaidu-zelar
      #     minimum-approvals: 1
      #     exclude-workflow-initiator-as-approver: false
      #     additional-approved-words: ''
      #     additional-denied-words: ''
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      - name: Publish
        run: dotnet publish -c Release -o ./publish
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: zelar11
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
          package: ./publish 
